### ISSUE TITLE
Errors when adding time

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#111]
When adding the number first and then the unit on a waiting Node, the number is not saved and thus not displayed in the canvas. This happens for all type of units except Minutes. When opening the sidebar again for a waiting node , the number OR the unit is displayed, not both. However, If I start with the unit instead of number it all works ok.

**Comment by SjoenH** [comment]
@ntorsen ready in test.

**Comment by ntorsen** [comment]
working good in test
