### ISSUE TITLE
Toolbox should only show when users have edit rights

### ISSUE THREAD

**Issue by SegarJJ** [equinor/MAD-VSM-WEB#114]
The toolbox is showing for projects where you don’t have edit rights, and it should not.

Related: The tool tray will not be presented on an editable VSM if the user previously was viewing a read-only VSM.  The tool tray should be visible in this condition.

**Comment by SegarJJ** [comment]
I would like to test this in a few methods before we close it out. @ntorsen might help as well.

**Comment by SjoenH** [comment]
Seems to be working as expected. @ntorsen Could you verify?

**Comment by ntorsen** [comment]
Works here as well. Toolbox appears only when having edit rights.

**Comment by SjoenH** [comment]
Super :muscle: closing this then.
