### ISSUE TITLE
As a user I want to duplicate a project (with all features other than PQI's) so that I can adjust it to my own needs

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#117]
Click on the duplicate button in the vsm-title-dropdown to create a new VSM with the same cards.
Note; Questions, Ideas and Problems are not copied, and it is not shared with anyone by default.

- [x] #147

**Comment by SjoenH** [comment]
@ntorsen Ready for testing :100:

**Comment by SjoenH** [comment]
@ntorsen Updated: Try to break it now :muscle:

**Comment by ntorsen** [comment]
I'm not able to recreate the problem from yesterday. Working very good :)

**Comment by SjoenH** [comment]
Ok, super. :muscle: 

@knudsvik & @askbulle 
NEW Duplicate feature is ready for testing in QA. What do you think?

**Comment by knudsvik** [comment]
Will check it asap

**Comment by knudsvik** [comment]
QA:

- The title on a duplicate would be better if it was "Title (Duplicate of xx)" instead of "Duplicate of Title (xx)"
- Copying without PQI is fine for the first release. We are adding a user story in the backlog to also include PQI (low pri) and sharing rights, see #144 
- Is the original project reference saved as data in the database? This could prove value in the future (version history etc)
- The "Pop-up dialogue when creating new VSM" feature (#145) should also include naming of duplicates (enforce name change?)

**Comment by SjoenH** [comment]
> Is the original project reference saved as data in the database? This could prove value in the future (version history etc)

No, this is strictly a new project with the same cards. The only link we have for now is the title, and it can be removed/changed by the user.

**Comment by SjoenH** [comment]
> The title on a duplicate would be better if it was "Title (Duplicate of xx)" instead of "Duplicate of Title (xx)"

New build with this change ready in QA @knudsvik

**Comment by SjoenH** [comment]
> Is the original project reference saved as data in the database? This could prove value in the future (version history etc)

Created a task for it #147 
@knudsvik do you consider it a blocker for this feature, or may we add it later?

**Comment by knudsvik** [comment]
> Created a task for it #147
> @knudsvik do you consider it a blocker for this feature, or may we add it later?

Yes, we consider this as a blocker for the initial release

**Comment by SjoenH** [comment]
Ok, @Magos you have an ETA on when you could add the extra field? #147

**Comment by SjoenH** [comment]
Ready for testing in QA. @knudsvik 
![image](https://user-images.githubusercontent.com/3164065/132224167-081780f5-50a7-436a-ab16-e3470d519365.png)
Duplicates should now have a new field in the db called `duplicateOf`. Verify by looking at the response object when fetching a project.

 @ntorsen let's do a quick regression test in QA for this. If all is good, we will try to release tomorrow.

**Comment by knudsvik** [comment]
Looks good! Checked the QA database, easy to find and use the duplicateOf data. Thumbs up!

**Comment by ntorsen** [comment]
> @ntorsen let's do a quick regression test in QA for this. If all is good, we will try to release tomorrow.

Looks good 👍

**Comment by SjoenH** [comment]
Released to prod :muscle:
