### ISSUE TITLE
Unlinking task throws an error

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#120]

**Comment by SjoenH** [comment]
Fixed by  #135

**Comment by SjoenH** [comment]
@ntorsen Ready for testing together with #132 in Test-environment. 
This is only a front-end change. So we should be good to go.

If you approve, feel free to promote it to QA and Prod: https://console.radix.equinor.com/applications/vsm/jobs/new?pipeline=promote&deploymentName=test-njsmu-afemj8dj&fromEnvironment=test

**Comment by ntorsen** [comment]
Working good in test.
Promoted to Prod
