### ISSUE TITLE
Side bar hides message that other user(s) made changes in VSM

### ISSUE THREAD

**Issue by askbulle** [equinor/MAD-VSM-WEB#130]
**Describe the bug**
Side bar hides message that other user(s) made changes in VSM.

**To Reproduce**
1. Two users open same VSM, both with write access
2. add some cards 
3. User 1 opens side bar
3. User 2 adds another card (or other change)

**Expected behavior**
Change message visible regardless of having side bar open

**Comment by SjoenH** [comment]
@ntorsen Ready in test-environment. Let me know if you need help testing it (multiplayer).

**Comment by ntorsen** [comment]
> @ntorsen Ready in test-environment. Let me know if you need help testing it (multiplayer).

I think I need help testing this 👍
