### ISSUE TITLE
Thorjan & I tested. Really nice feature. The bugs are should not stop us from releasing

### ISSUE THREAD

**Issue by askbulle** [equinor/MAD-VSM-WEB#131]
Thorjan & I tested. Really nice feature. The bugs are should not stop us from releasing 
However, when side bar is open it is not possible to see the little black box alerting to changes other user(s) have made
#130

_Originally posted by @askbulle in https://github.com/equinor/MAD-VSM-WEB/issues/92#issuecomment-909146706_

**Comment by askbulle** [comment]
User unable to delete issue :-)

**Comment by SjoenH** [comment]
I don't think it's possible to delete issues. But it doesn't matter. Closing them is good enough :)
