### ISSUE TITLE
Make the Changelist public

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#136]
Fixed in 1afb860aeae9695dfabbaf8cbf6c8ed9085f7fb2

**Comment by ntorsen** [comment]
No problem with the changelog if you view it on the startpage. However, if you go into one of the projects and by the dropdown list on the top right side, I get this message 
![image](https://user-images.githubusercontent.com/89014017/131788530-515620af-339f-4fda-a025-46edb3238a78.png)

Is the changelog only supposed to be available on the startpage? @SjoenH

**Comment by SjoenH** [comment]
No, good catch!

**Comment by SjoenH** [comment]
Please test again now @ntorsen

**Comment by ntorsen** [comment]
> Please test again now @ntorsen

Working good 🥇
