### ISSUE TITLE
Keep link to old project in project metadata

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#147]
New field `duplicateOf` in project metadata
```json
    name: "New project"
    duplicateOf: "Old project",
```

**Comment by Magos** [comment]
Da har jeg startet [en build med denne i](https://dev.azure.com/statoil-mad/VSM/_build/results?buildId=28413&view=results). Dette er migreringsscript for SQL-serverne
[DuplicateOf_column.zip](https://github.com/equinor/MAD-VSM-WEB/files/7115783/DuplicateOf_column.zip)
det er idempotent og kan kjøres flere ganger.
