### ISSUE TITLE
GetProjectWithObjectsById burde ikke svare Internal server error når bruker spør om prosjekt som er slettet

### ISSUE THREAD

**Issue by Magos** [equinor/MAD-VSM-WEB#150]
For prosjekter som ikke finnes lenger burde denne metoden ikke føre til Null Reference Exception, men heller identifisere at prosjektet er slettet og gi en bedre statuscode.

**Comment by Magos** [comment]
Har en retting på dette i branch bug/vsm-150, men migrerer den ikke til dev før @SjoenH evt. er ferdig med forrige branch.

**Comment by SjoenH** [comment]
Siden dette kun skal være en back-end fix så kan du release til Test-miljøet og få @ntorsen til å teste.

**Comment by ntorsen** [comment]
Looks good in test 
![image](https://user-images.githubusercontent.com/89014017/132685325-a3c7bbc3-fcec-4104-b8a1-a4a41b9b25be.png)
