### ISSUE TITLE
Information/Tutorial for new features

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#151]
**Describe the solution you'd like**
As a user I want to get a pop-up message (with update details) when opening flyt.equinor.com for the first time after a new feature release so that I know about new features I can use.

Only for major releases? Include bugs? Link to changelog?

**Comment by SjoenH** [comment]
Duplicated by #196. Maybe we should close this one? @knudsvik

**Comment by SjoenH** [comment]
Also, this one is in high-priority but not in our backlog.

**Comment by knudsvik** [comment]
Agreed. Closing this.
