### ISSUE TITLE
Add R to PQI's (R for Risk)

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#155]
**User input (if feedback)**
HI, This is very good tool. I am using it for VSM process in the subactivity. you have problem, idea and questions. 
 We have some risks associated and would like to have it in the drop down menu. RISK
in addition, the dropdown menu is not intuitive, i started writing in that and then clicked save. nothing was saved. 

Hope to see the possibility to choose risk in the subactivity. 
Best Regards
Chetna Shukla

**Sharepoint ID(s) (if feedback)**
82

**User story**
As a user I want to add risks to process elements so that I can follow up risks

Todo:
- [x] API support - Add new taskType
- [x] Front-end implementation

**Comment by SjoenH** [comment]
@Linedueo what color would fit?

**Comment by SjoenH** [comment]
![primary](https://user-images.githubusercontent.com/3164065/135403119-9ff3b808-0ce5-4e0b-a1a3-b69a8c530fb0.png)

**Comment by SjoenH** [comment]
@ntorsen this is ready for testing in dev environment. https://web-vsm-dev.radix.equinor.com

**Comment by ntorsen** [comment]
> @ntorsen this is ready for testing in dev environment. https://web-vsm-dev.radix.equinor.com

I don't get Risk up in dev env. Has there been any changes to it? @SjoenH

**Comment by martabenthem** [comment]
@ntorsen the changes have been pushed again to dev.

**Comment by ntorsen** [comment]
@martabenthem looks good in dev 👍

**Comment by SjoenH** [comment]
@Magos I think we are ready in QA for this? Was just a small database addition if I remember correctly.
@martabenthem please promote and move :)

**Comment by Magos** [comment]
Yes, Risk type is already added to databases for Dev, Test and QA.

**Comment by ntorsen** [comment]
Tested in QA env, working good.

**Comment by SjoenH** [comment]
@equinor/flyt-product-owners I mentioned this one in our Stakeholder meeting, but forgot to add a comment here. :) 
This is ready for testing.

**Comment by knudsvik** [comment]
looks good! You may release 🙌

**Comment by SjoenH** [comment]
💪 Let's get this one out. 
@Magos please report back when the database changes are done in prod. (I don't think we need any downtime for that, since it is just adding another `taskType`?)

**Comment by Magos** [comment]
@SjoenH Prod is updated now. No downtime for this, indeed.

**Comment by SjoenH** [comment]
This feature is now released to production. @equinor/flyt-product-owners
