### ISSUE TITLE
DuplicateOf not registered

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#202]
**Describe the bug**
Several processes were duplicated today, none of them are flagged in the DuplicateOf column in backend. 

Eg. 467 is a duplicate of 466
468 and 469 are also duplicates.

**Comment by SjoenH** [comment]
Fixed and released to production-environment.

**Comment by SjoenH** [comment]
@ntorsen try to reproduce this, please.

**Comment by ntorsen** [comment]
> @ntorsen try to reproduce this, please.

In which environment can I try to reproduce this?

**Comment by Magos** [comment]
QA for instance. It should be supported on all environments now.

**Comment by ntorsen** [comment]
Not able to reproduce it, DuplicateOf gets registered.

**Comment by Magos** [comment]
@SjoenH Do we have any controls on caching of script files and such in browsers? Could some users be connecting with older versions of the front-end?

**Comment by Magos** [comment]
We've found a repro method:

1. Duplicate a process.
2. Rename the duplicate to something else.

Evidently, the frontend does not report the duplicateOf field back to the backend when updating, and the update method allows this field to be changed.
