### ISSUE TITLE
Security vulnerability in JwtBearer

### ISSUE THREAD

**Issue by Magos** [equinor/MAD-VSM-WEB#209]
Vulnerability reported by Snyk:
Microsoft.AspNetCore.Authentication.JwtBearer is an ASP.NET Core middleware that enables an application to receive an OpenID Connect bearer token.

Affected versions of this package are vulnerable to Improper Output Neutralization for Logs. It adds JWT tokens into the logfile if those can't be parsed correctly.

    Introduced through
    Microsoft.AspNetCore.Authentication.JwtBearer@5.0.8
    Fixed in
    Microsoft.AspNetCore.Authentication.JwtBearer@5.0.9, @3.1.18, @2.1.19

**Comment by SjoenH** [comment]
Released
