### ISSUE TITLE
Why the dotted lines around 'logout' and 'duplicate' items?

### ISSUE THREAD

**Issue by SegarJJ** [equinor/MAD-VSM-WEB#211]
I can see the dotted lines around both of these choices, in the pulldown options in the main toolbar when looking at a VSM, but I am not sure why they are standing out from the rest of the options, is it intended to tell me something special?

**Comment by SegarJJ** [comment]
![image](https://user-images.githubusercontent.com/23700786/135082088-7fa0be0b-db22-4538-ae9e-d4bf97f074c1.png)

**Comment by knudsvik** [comment]
I had the exact same question to @SjoenH a couple of weeks ago.. answer: "Det er for keyboard navigasjon". It works somewhere, but not consistently..

**Comment by SjoenH** [comment]
It's a part of keyboard navigation hint that we get by using EDS components. 
Keyboard navigation is not currently up to par with https://www.a11yproject.com/

**Comment by SjoenH** [comment]
https://eds.equinor.com/guidelines/accessibility/#what-is-accessibility

**Comment by SjoenH** [comment]
Closing this since it's not an issue. (And not linked to POs sharepoint...)
I don't want to overwrite EDS-component functionality. We should rather create a task for 
improving accessibility.

**Comment by SjoenH** [comment]
Also, there's a related bug in EDS right now https://github.com/equinor/design-system/issues/605
