### ISSUE TITLE
When many participants are active in one project, the icons looks a bit weird.

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#216]
When many participants are active in one project, the icons looks a bit weird. ![Image](https://user-images.githubusercontent.com/25986427/135574472-e5d97194-29e8-4fde-af5d-f209360b9512.png) Is it possible to this any cleaner? E.g. having the owner as a separate, then stacking admins and collaborators or something? I guess the layout of the cards will have to change with #159, so could be addressed there.

_Originally posted by @knudsvik in https://github.com/equinor/MAD-VSM-WEB/issues/113#issuecomment-931948242_

Ideas:
- Include roles (owner/admin/contribnutor)
- Could the face/pictures come from Equinor?

**Comment by SjoenH** [comment]
I think the way GitHub does this looks great. 
![userDot-inspiration](https://user-images.githubusercontent.com/3164065/135591215-a927eb31-a594-4626-9a16-93ca61a3f355.gif)

Also, I think they are only showing 3-4 `user-dots`. 
Right now we are displaying all users, which quickly gets crowded.

Let's consider only showing a few, then a `(+3)`-icon or something...

**Comment by Linedueo** [comment]
<img width="1493" alt="Skjermbilde 2021-10-04 kl  12 57 29" src="https://user-images.githubusercontent.com/74361011/135839795-0b0943b5-845a-4420-81f6-e22c8d449de2.png">
@SjoenH same as #159 but I add it here as well cause its relevant

**Comment by SjoenH** [comment]
This was fixed by #219
