### ISSUE TITLE
Redesign `VSMCards component`

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#219]
![image](https://user-images.githubusercontent.com/3164065/135979172-482f630a-0e46-43e5-b91f-5aade4686862.png)

- [x] Move the `edited time` text up.  
- [x] Update `userDots` component to only show 3 users at a time.
- [x] Make the `userdots` component clickable. ⇾ open `AccessBox`- component in a scrim. Center on the page.
- [x] Create new `Label`-component
- [x] Create new `Labels`-component. ~~Display a maximum of 10 labels at a time.~~ Show them all. 
- [x] show the whole title for a card. No truncation. Wrap down to new-line.

These changes should cover #216. So remember to close that one after this is done.

**Comment by martabenthem** [comment]
https://www.figma.com/file/IkHwmIQrsT0iR34f5R5UnZ/VSM?node-id=2816%3A107643

**Comment by knudsvik** [comment]
As of today, the titles on the cards are truncated without any visual indications of it being truncated. There should be a visual indication, e.g. `...` and possibility to see the full title when hovering

**Comment by SjoenH** [comment]
@knudsvik 👋 
@Linedueo  suggests that we show the whole title for a card. No truncation. Wrap down to new-line.

**Comment by ntorsen** [comment]
This has been tested in Test env. 

Findings: When renaming the process with as many as 300 characters, the name "sticks" to the tile. 
However, if you put in a very long word, the name of the process will go out of the tile. See example below: 
![image](https://user-images.githubusercontent.com/89014017/139636964-5732a9c5-f1af-4632-b75b-d5bfa5507889.png)

Works good otherwise- only shows three user in tile, able to hover to see all user, can click this section and get pop-up of all users and what roles they have, also able to add more users here. 💯

**Comment by SjoenH** [comment]
Ping 🔔 @martabenthem
I tested the copy-link button, and it is copying the current URL, which worked when we have the share-box in the same page as the process, but need to be adjusted when used other places.
**Correct behaviour,** copy the link to the process.

So then we have two things to fix:
- [ ] Text-wrap 
- [ ] Copy-share-link

**Comment by ntorsen** [comment]
I'm guessing that the text-wrap will also fix that users are able to put process as favorite ❤️ ? @SjoenH 
Because that is not possible now.

**Comment by martabenthem** [comment]
@ntorsen you mean in case there is a very long word? If that's what you mean then yeah, the heart will be on the card so it will be possible to fave the process.

**Comment by ntorsen** [comment]
@martabenthem when adding a long word or a long word in a sentence, it was not possible to put the process as favorite. You can see this from the picture I attached above. However, I see that there has been made some changes now :-) 
![image](https://user-images.githubusercontent.com/89014017/139801759-eddf0bd2-6968-4608-a1e1-dd4ed2f8bff8.png)

**Comment by SjoenH** [comment]
The heart should probably not be centred with the text, but be aligned top like the other cards.

**Comment by SjoenH** [comment]
@ntorsen Ready for testing: https://web-vsm-test.radix.equinor.com

**Comment by SjoenH** [comment]
@ntorsen @Linedueo  Ready for testing: https://web-vsm-test.radix.equinor.com

**Comment by Linedueo** [comment]
@SjoenH ser bra ut!

**Comment by ntorsen** [comment]
@SjoenH working good 👍 
- Copy-share-link is working
- Can add users from main page (doesn't have to enter process to add users) 
- Three users is showing, when hovering all users will come up as well as clicking on right down side of the tile
- Text is within tile (used many characters)
- Heart when favoriting a process is aligned at the top

**Comment by martabenthem** [comment]
@askbulle @knudsvik this feature is ready for you to check 👍

**Comment by knudsvik** [comment]
It looks awesome! The only comment I have is that the following two notations should be the same word? Not directly related to this issue, also a problem with the current prod version. But should ideally be fixed, maybe in this PR?

![image](https://user-images.githubusercontent.com/25986427/140482334-72a0f478-5c04-4baa-a6c8-0045f3176b6c.png)

**Comment by martabenthem** [comment]
@knudsvik nice catch! I can easily modify it in this PR indeed.

**Comment by martabenthem** [comment]
@askbulle @knudsvik this feature has now been released.

**Comment by SjoenH** [comment]
@martabenthem remember to move the cards when the status updates. 😄

**Comment by martabenthem** [comment]
@SjoenH apparently if you reopen the issue by mistake the card is moved automatically to pending release. Closing the issue back does not move the card back to released.

**Comment by SjoenH** [comment]
Ah! That makes sense 😅
