### ISSUE TITLE
Search including & doesn't work

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#225]
Not sure if it's a bug or intentional but I wanted to search for some processes that have `P&I` in the title. I did not get any results, not with `"P&I"` either. I guess it's the `&` somehow making problems? This is the same search result from the power BI report:

![image](https://user-images.githubusercontent.com/25986427/136333749-f2f07323-21f6-42fc-a2b8-defa632a3dcc.png)

_Originally posted by @knudsvik in https://github.com/equinor/MAD-VSM-WEB/issues/113#issuecomment-937505363_

**Comment by ntorsen** [comment]
@Magos I don't think this is ready for testing. When searching for a name with & in it, I get almost all of the processes as search result. 
![image](https://user-images.githubusercontent.com/89014017/139663527-8f2886cf-ae27-445a-87e6-5f4901fe80a6.png)

**Comment by Magos** [comment]
> 
> 
> @Magos I don't think this is ready for testing. When searching for a name with & in it, I get almost all of the processes as search result. ![image](https://user-images.githubusercontent.com/89014017/139663527-8f2886cf-ae27-445a-87e6-5f4901fe80a6.png)

This part is a front-end issue, where the front end sends the parameters 
`?page=1&items=15&q=t&qa=&orderBy=modified`
but should send the parameters 
`?page=1&items=15&q=t%26qa=&orderBy=modified`

**Comment by SjoenH** [comment]
- [ ] Url-encode searchQuery

**Comment by ntorsen** [comment]
Works good in test now (for both &-sign and other signs) 👍 
![image](https://user-images.githubusercontent.com/89014017/139673646-0a56bc9d-84e9-4cd0-8844-e079786a98d9.png)

Search gives results when there is space between words and also when no space.

**Comment by SjoenH** [comment]
Ok, super 💪
