### ISSUE TITLE
Favourite a process from the canvas

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#252]
**User story**
As a user I want to mark a process as a favourite from the canvas so that I don't have to exit the process and find it again in the landing page to mark it

**Describe the solution you'd like**
A heart in the navigation bar - with a descriptive hover text

**User input**
Functionality; to set as favorite within Flyt. E.g. getting a link to a flyt from someone else and figure out that it was something to keep for later. Work-around is to search on Flyt-name on landing page and then save (heart")

**Sharepoint ID**
103

**Comment by SjoenH** [comment]
Unsure if we need design on this. The described solution sounds good to me. @Linedueo

**Comment by SjoenH** [comment]
@ntorsen 
Ready for testing in test environment

**Comment by ntorsen** [comment]
**Remarks for testing:** There is no problem setting a process as Favorite from current process. And it lands on 'See my favorite processes' page too. However, ❤-icon appears in To-be process as well, but it is not possible to set it as Favorite from this page. 
![image](https://user-images.githubusercontent.com/89014017/145975946-6a99a6bd-27d2-4fb8-b800-c9f8d5c31d56.png)
If a user is not supposed to be able to set a process as favorite from To-be, then it should not appear here. 

Also, I don't get any descriptive hover text as is mentioned in user story. 

@SjoenH

**Comment by SjoenH** [comment]
Good catch!
For other metadata-changes (name, access, labels) we have handled the to-be process and the current one as the same.
@Magos could you take a look at it?
- [ ] Favouriting a To-Be-process should be reflected in the current.

**Comment by knudsvik** [comment]
> * Favouriting a To-Be-process should be reflected in the current.

.. and vice versa ;)

**Comment by Magos** [comment]
Update to allow that in the backend is now live on test & QA levels.

**Comment by knudsvik** [comment]
> Update to allow that in the backend is now live on test & QA levels.

@martabenthem does that mean this is now ready for another test?

**Comment by Magos** [comment]
@knudsvik As far as I know, @SjoenH's work on the front-end is not published to those levels for testing. Might just wait for the new year to get that one together.

**Comment by knudsvik** [comment]
@Magos It was actually in Test 8 days ago so I think the work is done. The To-be issue was caught by @ntorsen when testing.

**Comment by SjoenH** [comment]
I'll get a new build out into Test asap.

**Comment by SjoenH** [comment]
Ready for testing @ntorsen https://web-vsm-test.radix.equinor.com

**Comment by ntorsen** [comment]
Able to set a process as favorite from both current and to-be canvas 👍
It lands on 'see my favorite processes' as expected. 

But there is still no descriptive hover text as mentioned in user story above @SjoenH  
If there has been decisions made that it is not necessary any more, then please discard this comment.

**Comment by SjoenH** [comment]
I've moved this to QA now. @knudsvik ready for testing.
I did not add the hover-text (as @ntorsen mentioned) to be consistent with what we have done for the front-page hearts. Let me know if this should be changed or not.
https://web-vsm-qa.radix.equinor.com

**Comment by knudsvik** [comment]
Awesome! Don't think the hover is necessary; self-explainatory and consistent both. Ready for release.
