### ISSUE TITLE
Changes in categorization page --> last modified

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#258]
**Describe the bug**
Changes in categorization page is not reflected in the Last modified data on front page

**To Reproduce**
1. Check last modified for a process on the front page
2. Open a process
3. Go to categorisation page
4. Make a change
5. Go back to the front page and check last modified date

**Expected behavior**
Last modified to be updated upon changes in categories page

**Comment by Magos** [comment]
Deployed to Dev environment and available to test there now. @ntorsen

**Comment by knudsvik** [comment]
This is actually an issue for the To-be process #192 as well when tested in QA now.

**Comment by ntorsen** [comment]
This is working as expected in Dev environment 👍 @Magos
