### ISSUE TITLE
Share access with multiple users effectively

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#268]
**User input**
We use Flyt in our team, and it can be quite slow to give the whole team access to all our processes.

Consider adding a bulk-import. For example comma separate users in the input-box.

**Sharepoint list ID**
94

**Comment by SjoenH** [comment]
Looking over my PRs... This one is ready to be moved into testing, but waiting on your "GO" @knudsvik & @askbulle 
![](https://user-images.githubusercontent.com/3164065/139064897-312d07aa-67b0-46bc-bca9-b492610d4a0e.gif)

**Comment by knudsvik** [comment]
@SjoenH I was not aware of this. No reason to just put it into testing?

**Comment by SjoenH** [comment]
Currently blocked by testing of #154, but will push out after 🚀

**Comment by SjoenH** [comment]
@ntorsen This is now ready for testing in [Test env](https://web-vsm-test.radix.equinor.com/) 💪 (together with the #154 and #275 )

See video for example use https://github.com/equinor/MAD-VSM-WEB/issues/268#issuecomment-1064837495
And please ask if you have any questions. :)

**Comment by ntorsen** [comment]
@SjoenH Test environment seems to have some problems. Inspect says code 200 OK, but no processes are visible 
![image](https://user-images.githubusercontent.com/89014017/158359129-058fb180-0439-4c48-a05a-d2da5bae479b.png)

**Comment by SjoenH** [comment]
@ntorsen I've added a fix for this. Ready in test now

**Comment by ntorsen** [comment]
Awesome, working great now ✨ @SjoenH

**Comment by SjoenH** [comment]
Thanks for testing 🥳 🚀 

@knudsvik @askbulle This is now ready in QA in case you want to give it a try. 👍

**Comment by knudsvik** [comment]
Looks good @SjoenH :)
