### ISSUE TITLE
Verify what code is currently running

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#275]
### User-story
As a tester,
I need to verify what features are currently running in the browser,
So that I can do a good test and test the right thing.

### Background
This is important to get in because of browser caching. How can someone verify that they are testing the correct build?
We need to be confident that what we are pushing to some environment is what is tested before releasing.

### Suggested solution
Show git commit in the dropdown. 
Make it so that clicking on it takes you to the commit in GitHub, where you can read more about it.

**Comment by SjoenH** [comment]
@Magos I've solving this by linking to the Git hash for the running code. We could do something similar for the back-end, but probably would need an endpoint to query for it.

**Comment by SjoenH** [comment]
We had some hiccups with the generation of new commitHash file, hijacking the latest commit in the main-branch (as seen in pr #379 ). Moving this back to in-progress to improve it a bit :)

**Comment by SjoenH** [comment]
@ntorsen ready for testing again :) Test environment

**Comment by ntorsen** [comment]
Working good in Test/QA environment 👍 @SjoenH 

(test env)
![image](https://user-images.githubusercontent.com/89014017/158821664-6c6b2216-3f57-4c67-a976-01dd6ec88d76.png)
(qa env)
![image](https://user-images.githubusercontent.com/89014017/158822864-f6cf6822-ad24-4493-8c68-420be9297b50.png)

(same commit in github)
![image](https://user-images.githubusercontent.com/89014017/158821509-e1002578-a088-4fc4-bf28-528bedf607de.png)

Same result for different browsers (Edge and Chrome).
