### ISSUE TITLE
Categorisation not working

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#289]
**User input**
Mapping categories to problems is not working

**Sharepoint list ID**
97

**Comment by smolvik1** [comment]
![categories_mapping](https://user-images.githubusercontent.com/36161719/140889343-ad114526-b054-4415-bfba-5e61738168c3.gif)

**Comment by SjoenH** [comment]
duplicate of #288

**Comment by SjoenH** [comment]
Hi. Thanks for the report. We are working on a fix.

**Comment by knudsvik** [comment]
Fixed upon release yesterday
