### ISSUE TITLE
SignalR services are still running in Azure

### ISSUE THREAD

**Issue by Magos** [equinor/MAD-VSM-WEB#293]
If SignalR support is being sunsetted, we should finalize cancelling these services at some point.

**Comment by SjoenH** [comment]
Yes. Just do it.
Better to create them again if we decide to use it.

**Comment by Magos** [comment]
Deleted services vsm-sr-prod, vsm-sr-qa, vsm-sr-test, vsm-sr-dev from the Azure resource groups.
