### ISSUE TITLE
Sharing with names instead of short name

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#299]
**User input**
Hi, sharing the VSM with others is very good, but having to use only the shortname to put in the ones you want to share with makes it slower than necessary. is it possible to have that function based on both shortnames and names?

**Sharepoint list ID**
100

**Comment by SjoenH** [comment]
Relevant issues #199 #197

**Comment by knudsvik** [comment]
Duplicate of #197 - will be followed up there.
