### ISSUE TITLE
My process dissappears from my-processes after it gets an to-be process

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#307]
If I create a new process and make a to-be process, this does not show in "See my processes". Newly created processes land on that page, but if you do something on the To-be, they will disappear from this page.

_Originally posted by @ntorsen in https://github.com/equinor/MAD-VSM-WEB/issues/192#issuecomment-976411874_

**Comment by Magos** [comment]
New version is out to fix this in dev, and [also building to Test](https://dev.azure.com/statoil-mad/VSM/_releaseProgress?_a=release-pipeline-progress&releaseId=220). Could you try it out, @ntorsen ?

**Comment by ntorsen** [comment]
Tried it out in DEV environment --> working good now @Magos  🥇

**Comment by ntorsen** [comment]
Seems to be working in test env as well 😃
