### ISSUE TITLE
Decide on how to present solved PQIRs in the categorization page.

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#308]
Bringing this to your attention again... @Linedueo @knudsvik @askbulle What happens in the categorization page?

_Originally posted by @SjoenH in https://github.com/equinor/MAD-VSM-WEB/issues/165#issuecomment-977652284_

**Comment by knudsvik** [comment]
Solved PQIR's should not show in the categorisation page.

**Comment by SjoenH** [comment]
Super. Here's the answer @martabenthem. Please filter them away in the categorization page.
@Magos I think it makes sense to do this in the front-end. Let me know if you object.
