### ISSUE TITLE
Missing roles and times when duplicating

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#323]
**User input**
We have duplicated a VSM and roles and time are not copied over. 
Is there a reason for this? Or could this feature be added?

**Sharepoint list ID**
113

**User**
Elisabeth Siem

**Comment by SjoenH** [comment]
Roles and times should be included... :thinking: 
I'll have to take a look.

**Comment by SjoenH** [comment]
Reproduce by duplicating a project. Roles and times are not moved over.

**Comment by knudsvik** [comment]
Relates to:
- #144

**Comment by knudsvik** [comment]
Covered by #144
