### ISSUE TITLE
Contributor access to process 824

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#327]
**User input**
Hei
Jeg er contributer på et flyt diagram men får  ikke editerer eller legge inn noe på dette? Andre som er contributers på samme flyt diagrammet har rettigheter til å editere?  Er det noen tilganger som jeg mangler?  Hilsen Nina

**Sharepoint list ID**
117

**User**
Nina Melbye Hansen

**Comment by knudsvik** [comment]
Wrong short name was used when providing contributor access. Would probably not been an issue when #197 is solved.

**Comment by SjoenH** [comment]
Ok, super. Thanks for checking. :+1:
