### ISSUE TITLE
Enter to close rename process dialogue box

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#361]
**Describe the solution you'd like**
When renaming a process, hitting enter should close the dialogue box

Todo:
- [ ] Make the dialog a bit larger
- [ ] Enter to close the dialog

Requirements for testing:
- [ ] Pressing enter should close the dialog box
- [ ] Pressing escape should close the dialog box
- [ ] Pressing the 'x' should close the dialog box
- [ ] Pressing outside the dialog should close the dialog box
- [ ] User should be able to rename a process by typing in the input-field

**Comment by knudsvik** [comment]
quick-fix @SjoenH ?

**Comment by SjoenH** [comment]
Discussed if we want to simplify a bit. Removing the dialog box and edit text directly

**Comment by SjoenH** [comment]
Note, that we today can close the edit box by pressing escape, clicking the `x` or clicking outside the edit box.
Enter-key would be an intuitive, and quick thing to add. 

Removing the dialog box and editing the text directly would take a bit more time, but still a small task.

**Comment by askbulle** [comment]
Connected to #417 ?

**Comment by SjoenH** [comment]
@askbulle Yes, what's described in #417 would render this #361 unnecessary. So we would need to choose one over the other.

**Comment by knudsvik** [comment]
@SjoenH Could not both be possible, or is it bad practice to have same function two places? If not, I would prefer #417 I think. @Linedueo : What do you think?

**Comment by SjoenH** [comment]
Of course, we could have both, but I would advise against it.
I would also vote for #417.

**Comment by Linedueo** [comment]
I agree that #417 would be the better option and not both.

**Comment by askbulle** [comment]
I also prefer #417
