### ISSUE TITLE
Improve API release pipeline

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#377]
We need to look into improving the release pipeline so that a release can be done in an expected timeframe.

The main issue is situations where APIM update fails to find the swagger.json file as a basis for its update.
In order to fix this, we are experimenting with adding a Webserver warmup step to our deploy process. This will wait until the webserver is responding with files before starting the APIM update.

**Comment by SjoenH** [comment]
@Magos feel free to update this with more information about the issue. 🙇

**Comment by SjoenH** [comment]
@Magos I see this is moved into test. Did you figure something out ? :)

**Comment by ntorsen** [comment]
Is this something I can test? And if so, how can I test it? @Magos @SjoenH

**Comment by SjoenH** [comment]
No. @ntorsen  I'm not sure what @Magos have done.

**Comment by Magos** [comment]
So far I've added webserver warmup steps to our releases to make sure we don't start the APIM update before the webserver has restarted. This story is just to track how that change is performing - if we're happy with it after a few releases it'll go to Released.

**Comment by ntorsen** [comment]
Maybe we can put this to "Pending release" column then? @Magos @SjoenH

**Comment by SjoenH** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/3164065/160347846-0f0be06b-54d8-4c9a-8e73-6be3fbe23b1b.png">

The warmup webapp step has been added.

**Comment by SjoenH** [comment]
It worked! 🥳
