### ISSUE TITLE
The process order on the front-page is wrong.

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#378]
Knudsvik reports that
> Doesn't seem like any ordering works, tried to change to Alphabetically etc, no changes.

We expect latest changed process should show first as default, unless any other order-method is selected.
![Screenshot 2022-03-16 at 14 12 58](https://user-images.githubusercontent.com/3164065/158597727-ff8c9151-c6ac-44b0-aed6-b80ef0b75074.png)

**Problem:**
When the UI is set to a different order by parameter, that appears in the URL of the browser but doesn't appear to get passed to the API.

**Comment by knudsvik** [comment]
Doesn't seem like any ordering works, tried to change to Alphabetically etc, no changes.

**Comment by dansvend** [comment]
Fix is now built to QA. Ready for testing @ntorsen 💪

**Comment by ntorsen** [comment]
@dansvend Tested in Qa environment, made a new process, look at Last modified and it appear first on the 6th page
![image](https://user-images.githubusercontent.com/89014017/158758879-05dd9d84-6a82-48c1-8447-5f90c341190c.png)

**Comment by SjoenH** [comment]
@dansvend Does it behave the same in another environment? If I remember, we did notice some differences between Test and QA wrt sorting. ref https://github.com/equinor/MAD-VSM-WEB/issues/154#issuecomment-1061789928

**Comment by Magos** [comment]
To rule out the un-migrated stored procedure as a cause, I have migrated it to every environment (including QA) now.

**Comment by SjoenH** [comment]
Looks like that fixed it @Magos

**Comment by SjoenH** [comment]
@ntorsen Ready for testing again 😅

**Comment by dansvend** [comment]
Sorting on "Date created" still doesn't seem to work in QA environment.
Created a new process at 09:48. Screenshot taken an 09:49. When sorting by "Date created" it shows as the 11th process.
![image](https://user-images.githubusercontent.com/47424077/158772608-315b7b7f-fb1d-4e3e-84d5-ede276833d40.png)

**Comment by ntorsen** [comment]
Last modified and Alphabetically works @SjoenH @dansvend 
Opened a new process and also modified an already created process, both appear first when viewing Last modified:
![image](https://user-images.githubusercontent.com/89014017/158826496-4161dc08-bfa2-4597-a62d-fd1685f810eb.png)

And also before testing, did a check/verification on what fix was committed. 🤩👌
![image](https://user-images.githubusercontent.com/89014017/158826682-4cea521f-f521-491f-ad03-d3287b26f8c2.png)

**Comment by SjoenH** [comment]
Moving this into prod now.
