### ISSUE TITLE
Sorting on "Date created" is not correct

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#382]
Sorting on "Date created" still doesn't seem to work in QA environment.
Created a new process at 09:48. Screenshot taken an 09:50. When sorting by "Date created" it shows as the 11th process.
![image](https://user-images.githubusercontent.com/47424077/158772608-315b7b7f-fb1d-4e3e-84d5-ede276833d40.png)

_Originally posted by @dansvend in https://github.com/equinor/MAD-VSM-WEB/issues/378#issuecomment-1070551608_

Depends on #383

**Comment by ntorsen** [comment]
This does not seem ready for testing... Tried both test and qa environment @SjoenH @Magos

**Comment by SjoenH** [comment]
Not sure why it was in test column... 🤔  so moving it back 😄 

@Magos Have you looked into this issue?

**Comment by Magos** [comment]
In my testing yesterday it was successfully sorting on create date - note that it sorts oldest first. If we want to switch to newest first that is a fairly simple fix. 

There was some messed up data from the period where projects were being created with default datetimes, which I believe I have corrected now today.

**Comment by ntorsen** [comment]
In test environment it looks like this for me:
![image](https://user-images.githubusercontent.com/89014017/159703197-54d630f2-ee14-4bcf-9b3b-729e6530bf42.png)
@Magos

**Comment by Magos** [comment]
As far as I can see, sorting is correct on test. What is the error in this case? 
If you're missing a "created x days ago" text similar to the modified sorting, that sounds like an @dansvend job.

**Comment by ntorsen** [comment]
Yes, missing that "created x days ago" text and the circle with a letter on the bottom right side of card, who created it and which users it is shared with. 
![image](https://user-images.githubusercontent.com/89014017/160099188-6f871acd-849f-42f6-acab-62a3e83bb28b.png)

**Comment by SjoenH** [comment]
Yes, #383 should cover the above @ntorsen :)

**Comment by SjoenH** [comment]
@Magos I believe (as you suggested) that it should be the oldest last. @knudsvik Do you have any preference here?

**Comment by SjoenH** [comment]
@Magos let's show the newest first.

**Comment by Magos** [comment]
Updated backend to sort newest first when using date created as the sorting field. Update has been pushed to dev, test, QA environments.

**Comment by ntorsen** [comment]
No change when selecting between 'Last modified', 'Date created' and 'Alphabetically'. Processes are on stand-still.
Same behavior in test and in Qa.

**Comment by dansvend** [comment]
@ntorsen @Magos Sorry for that. I was a little too quick releasing #175 into test and QA so that's why it didn't work when you tested this feature. I will build #383 to test and QA and will notify you after it's ready 🚀

**Comment by dansvend** [comment]
@ntorsen #383 is now built to test and QA, so this fix should now work as expected. Ready for testing 💪

**Comment by ntorsen** [comment]
@dansvend working good in test and QA 💪
