### ISSUE TITLE
Users and sharing not showing on front page

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#383]
**Describe the bug**
This is how it looks now:
![image](https://user-images.githubusercontent.com/25986427/158970747-e5aad204-f54e-4473-85f4-382f789f58f5.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/25986427/158971364-3dc42bc2-4fd1-4786-87f4-ed25b716a620.png)

**Comment by SjoenH** [comment]
Thank you for noticing.
@Magos can you take a look at this? It's the same for all environments.

Note that userAccesses is returned empty 🤔 
```json
 {
    "vsmProjectID": 847,
    "name": null,
    "isFavorite": false,
    "duplicateOf": null,
    "toBeProcessID": null,
    "currentProcessId": null,
    "objects": [],
    "created": "0001-01-01T00:00:00+00:00",
    "updated": "2022-03-14T11:32:38.6568405+00:00",
    "updatedBy": "HSJO",
    "userAccesses": [],
    "labels": []
}
```

**Comment by Magos** [comment]
I've built a new version to dev environment now that is returning useraccesses, _including the owner_.  However, the front page is not showing these there either. Is there a front-end dependency on the old "created" changelog object, @SjoenH ?

**Comment by SjoenH** [comment]
Thanks for this @Magos 🙇 

I'll take a look 😄

**Comment by dansvend** [comment]
@Magos Can you release API changes to test and QA as well? Changes works good in dev💪

**Comment by Magos** [comment]
API changes are now deployed to test and QA environments.

**Comment by dansvend** [comment]
Thanks @Magos 💪  This is now deployed to QA. Can you test this in QA @ntorsen ?🙌

**Comment by SjoenH** [comment]
### Todo:

**API**
- [ ] fix `updated` field - show correct date on create and update of process

**Front-end**
- [ ] Update to match new response structure

**Comment by SjoenH** [comment]
API changes should also cover #382

**Comment by Magos** [comment]
API update is now live on dev, test and QA environments. @dansvend.
I will be going through the data of existing projects that have a default value for their updated/updatedBy fields through SQL.

**Comment by dansvend** [comment]
Very good! Thanks @Magos 🙏

**Comment by ntorsen** [comment]
Working good in test and QA @dansvend 😊

**Comment by dansvend** [comment]
Nice! Thanks for testing @ntorsen 😊
