### ISSUE TITLE
Missing loading spinner when creating new project

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#388]
User might spam the button if the api is slow to respond. Let's add a loading spinner to show that we are working on it.

**Comment by knudsvik** [comment]
This hit me hard 🗡️ ... Probably had to delete 15 processes after the demo today

**Comment by SjoenH** [comment]
The log showed around 60 requests that minute to create a new process. Took just under 2 minutes before the API churned through it all... 👀

**Comment by SjoenH** [comment]
I've Refreshed the styling to match what's in Figma and disabled the button when it is sending the request.

https://user-images.githubusercontent.com/3164065/160115329-ce50e22d-6c66-47ae-86f9-cf64b924288a.mov

Ready for testing in QA. @ntorsen @knudsvik

**Comment by ntorsen** [comment]
Working good in QA for me 👍

**Comment by knudsvik** [comment]
Looks good! 🥳
