### ISSUE TITLE
Not able to delete process if it has categories or labels.

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#396]
Cannot delete process if:
- Tasks in the process have been categorized.
- Labels have been applied to the process.

**Comment by ntorsen** [comment]
@SjoenH can you give me more information what this is regarding? 
Tested in test and Qa, and I don't have problem deleting processes.

**Comment by SjoenH** [comment]
Okay I guess it might have been @SegarJJ  that experienced this bug. 

@Magos Do you have an input on when this was a problem?

**Comment by Magos** [comment]
In production, deleting a process should currently fail if

- Tasks in the process have been categorized.
- Labels have been applied to the process.

The fix is currently active on dev, test and QA environments.

**Comment by SjoenH** [comment]
Let's update this story to reflect what is fixed and needs to be tested before releasing.

**Comment by SjoenH** [comment]
I updated the main text, @Magos & @ntorsen, give a thumbs up if this looks correct.
