### ISSUE TITLE
Versioning not working

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#398]
**Describe the bug**
After 0.2.19 release it seems like versioning is not working as expected. I did an update on process 308 today, but if I go back to previous versions it still displays the current process.

**Comment by SjoenH** [comment]
@Magos I might need some help looking into this 🤔

**Comment by SjoenH** [comment]
I reproduced it by creating a new process, waiting, then making an edit. 
Selecting the previous version looks the same as the current.
![image](https://user-images.githubusercontent.com/3164065/160588609-1eecbc6e-b3c4-48eb-9e63-e255f7e33c5c.png)

**Comment by SjoenH** [comment]
@knudsvik ready in QA

**Comment by knudsvik** [comment]
Looks good @SjoenH

**Comment by Magos** [comment]
Released 12:16.
