### ISSUE TITLE
Move around canvas with right mouse button

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#399]
**User story**
As a user I want to move around the canvas with holding right mouse button as well as left so that it is similar to Miro behaviour (without the menu popping up).

![image](https://user-images.githubusercontent.com/25986427/160774435-67f61f2b-9967-4eec-9af7-f0a430b21b71.png)

**Comment by knudsvik** [comment]
@SjoenH @dansvend  Quick-fix?

**Comment by SjoenH** [comment]
Unsure about the implications of this ux change. 🤔  @Linedueo 

Right dragging in Miro functions the same as Left dragging in Flyt.
Miro has select on left drag as a default. So it makes sense in that tool, but not sure if it fits Flyts ux.

Not sure how easy it is to add, but probably not too long.

**Comment by knudsvik** [comment]
It is possible to right drag in Flyt today as well.. the only issue is that when you let go of the mouse button, a menu pop-ups. This menu does not add any value, so I was just wondering if it's easy to just disable that popup...

**Comment by SjoenH** [comment]
Ah, I see!

Yes, probably a quick fix. I just haven't thought about dragging with right-click before. 😅 

Let's add the quick-fix label, and rather remove it if we find out that it isn't

**Comment by SjoenH** [comment]
@ntorsen @knudsvik Ready for testing in QA 💪

**Comment by knudsvik** [comment]
LGTM
