### ISSUE TITLE
Version history artefact

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#404]
**Describe the bug**
I was browsing the version history of process 1174 today when I noticed something strange. When looking at it in [day resolution](https://flyt.equinor.com/process/1174?resolution=day&version=2022-03-16T10%3A46%3A41.035Z), 2 versions are showing (16.03.22 and NOW). When looking at it in [hour resolution](https://flyt.equinor.com/process/1174?resolution=hour&version=2022-03-16T10%3A46%3A41.035Z) though, 16.03, 24.03 and NOW is showing (with some strange format on the hours). On the [Month resolution](https://flyt.equinor.com/process/1174?resolution=month&version=2022-03-16T10%3A46%3A41.035Z) I only have the NOW (should probably have March there as well?).

**Screenshots**
![image](https://user-images.githubusercontent.com/25986427/161696673-fc8760d1-1ee1-4781-b1dd-716d503068b5.png)

![image](https://user-images.githubusercontent.com/25986427/161696644-aa9b4609-beef-452c-945a-8931f418e890.png)

**Comment by SjoenH** [comment]
I think this is correct, but might be wrong.
I'll try to explain, and then we can decide if this is something we want to improve 💪 

Day view: We have two different days with changes. (16.03 and 24.03) The last day would be the same changes as we see today, so we replace it with the `NOW`-pin.

Hour resolution would show 3 different hours with changes. The `16.03 at the 11th hour`, `24.03 at the 12th hour`, and `24.03 at the 14th hour`. 
 And we replace the last change with NOW.
You mentioned that the hours looked strange? We could change the formatting if you want.

In the month view:
The latest change is from `2022-03-24T13:05:57.285Z` which is last month, but still the `NOW` change.
And we don't have any changes from an earlier month.

Hope that sheds some light on it 😅 
Let me know if there is something that we want to improve.

**Comment by knudsvik** [comment]
Ahh, now I understand. It is behaving like intended :)
