### ISSUE TITLE
Owner cannot delegate roles from landing page

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#410]
**User input 1 (by Fredrik Liknes- sharepoint ID142)**
As a owner of a process mapping in Flyt I would like to be able to add other users as admins. I get the error message "You need to be owner or admin to manage sharing"  when attempting to add new users.

https://user-images.githubusercontent.com/3164065/165730867-db262d6b-a1a4-43b0-84f6-ceeac7980d95.mp4

**Comment by knudsvik** [comment]
Video from user:
https://user-images.githubusercontent.com/25986427/165230408-174dbf61-1bdd-4771-901a-988e6eebd148.mp4

I am having the same problem as the user, cannot add users when I am owner, but only from the landing page, it works when in the canvas.

**Comment by dansvend** [comment]
Fix is deployed to DEV-, TEST- and QA-environments and is ready for testing @ntorsen  🧪

**Comment by dansvend** [comment]
Seems like it's ready to be deployed to production then. Do you want me to deployed this to production @askbulle @knudsvik ? 🚀

**Comment by knudsvik** [comment]
> 

Sure @dansvend. Good to remove the service banner 💪
