### ISSUE TITLE
Card description in sidepanel is lagging behind

### ISSUE THREAD

**Issue by dansvend** [equinor/MAD-VSM-WEB#411]
**Describe the bug**
Card description in sidepanel is lagging behind.
When clicking on `Card A` on the canvas to edit the description from `Old` to `New`, `Card A` on the canvas updates to display the correct text, `New`. If I then dismiss the sidebar and then click on `Card A`on the canvas again, the description in the sidebar is showing `Old`.

**Expected behavior**
I expect the description in the sidebar to be in sync with what is saved in the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/47424077/165081290-02ec5698-512a-418e-8461-d04b88fd7124.png)

**Additional context**
Can be fixed by invalidating the query of the description text when dismissing side panel

**Comment by ofredstie** [comment]
Seems to originate from VSMSideBar, line 25, fetchedVSMObject has the dismissed description.



![Image](https://user-images.githubusercontent.com/3359842/221138888-4f18ef8a-3c6b-478e-903b-880050250849.png)

**Comment by Sayyare** [comment]
Is this task ready to test?

**Comment by Sayyare** [comment]
Tested in Test environment, works good. @ofredstie & @dansvend 🐱‍🏍

**Comment by SayyareHamit** [comment]
@ofredstie Can you please build Test environment for this task as well?

**Comment by ofredstie** [comment]
@SayyareHamit 

This is ready for testing now. 
The fix should impact only the side panel component. 
Focus testing on adding cards, adding and altering description followed by closing the card again. Verify that when opening the card once more the description should match the latest change.

**Comment by SayyareHamit** [comment]
works good in Test environment. @ofredstie 🐱‍🏍
