### ISSUE TITLE
Add link prompt visual bug

### ISSUE THREAD

**Issue by dansvend** [equinor/MAD-VSM-WEB#419]
**Describe the bug**
The "Add link"-prompt displays other content below.

**To Reproduce**
Add a link to a card that includes time and role fields.

**Expected behavior**
The "Add link"-prompt is the only thing that should be shown when adding a link.

**Screenshots**
<img width="382" alt="Uten navn" src="https://user-images.githubusercontent.com/47424077/167137606-643b66d7-b49b-44a6-8aeb-139f62ce14c8.png">

**Additional context**
Introduced with issue #175

**Comment by Sayyare** [comment]
Working as expected in Test environment. @ofredstie & @dansvend 🐱‍👤

**Comment by dansvend** [comment]
@Sayyare This is not working in test environment as the code is not running there yet as discussed on Slack. I think it's a good practice to never test a feature before. there's a message from the developer which includes version and build number or commit hash and verify that it's the that's deployed to the test environment from the menu in the upper right corner of web apps or in the `About` screen in mobile apps.

**Comment by SayyareHamit** [comment]
@ofredstie  Is this ready to test? If yes, can you please build Test environment that I can test it soon? ✨

**Comment by ofredstie** [comment]
@SayyareHamit 
This is ready to be tested now. 
"Risks" and "Add question, idea..." should not be visible now when adding a link.
