### ISSUE TITLE
Duplicate cards in process 

### ISSUE THREAD

**Issue by knudsvik** [equinor/MAD-VSM-WEB#444]
**User input 1 (by Fredrik Liknes- sharepoint ID166):**
As a user of Flyt I would like to duplicate cards in my process for reoccuring events to save time during mappings.

**User input 2 (by Marius Hegdal- sharepoint ID167):**
enable possibilities to copy/paste cards

**User input 3 (by Lise Storhaug Ekeland, Geir Lea Berge, Henriette Eidsnes):**
Ikke mulig å kopiere innhold i en eksisterende boks inn i en ny og gjøre endringer.. Eller finnes et eget triks?

**Comment by nesadrian** [comment]
Duplicate of #789 #800
