### ISSUE TITLE
Adjust HTTP headers to improve security

### ISSUE THREAD

**Issue by dansvend** [equinor/MAD-VSM-WEB#506]
HTTP headers which should be adjusted can be seen at [Security Headers](https://securityheaders.com/).

**Comment by dansvend** [comment]
@Sayyare 

This is ready for testing 👩‍🔬 A general test should be sufficient. Logging out and in again. Also try to log in from inkognito mode. Test the functionality. Thanks 🙏 

```
-----------------------------
| Platform     | Web        |
| Version      | 0.2.25     |
| Commit       | bc970bd    |
| Environment  | QA         |
-----------------------------
```

**Comment by Sayyare** [comment]
Working as expected in QA environment.  @dansvend 🐱‍🏍
