### ISSUE TITLE
Patch vulnerabilities

### ISSUE THREAD

**Issue by ofredstie** [equinor/MAD-VSM-WEB#511]
![image](https://user-images.githubusercontent.com/3359842/229500967-59078981-21c5-4135-81e4-9b602d3fbae6.png)

https://app.snyk.io/org/flex-hxq/project/8a1fedef-7776-4fb3-b528-ec14a94dc003

https://app.snyk.io/org/flex-hxq/project/c4636945-acfb-4614-9d66-f50e26bafde2

**Comment by ofredstie** [comment]
@SayyareHamit 

This patch is ready to be tested now. 
Updated Node version from 18.14.1 to 18.15.0 to fix vulnerability. 


```
-----------------------------
| Platform     | Web        |
| Environment  | Test       |
| Version      | 0.2.25     |
| Commit       | 380c457    |
-----------------------------
```

**Comment by SayyareHamit** [comment]
Working as expected in Test environment. @ofredstie 🐱‍💻
