### ISSUE TITLE
Feat: Have supporting text on the canvas in order to guide users

### ISSUE THREAD

**Issue by KaterynaBasik** [equinor/MAD-VSM-WEB#712]

**Comment by QiJin-Bouvet** [comment]
Some proposals for this feature:
- Show the supporting text in grey on both the card itself and the description area in the sidebar of the card
- Once user type something in the description area, the supporting text disappear, and user input shows in black
- Specific supporting text for each green card
- Specific supporting text for each type of cards: Main Activity card, Choice card, Sub Activity card,  Waiting card

**Comment by AnjaliPandit20** [comment]
@KaterynaBasik : As mentioned in the backlog refinement call, closing this issue as this resolved in 759.
https://github.com/equinor/flyt/issues/759
