### ISSUE TITLE
Delete edges bug

### ISSUE THREAD

**Issue by nesadrian** [equinor/MAD-VSM-WEB#847]

**Comment by luan-droid** [comment]
I don't understand this ticket/issue. Could someone provide more information? 

@ThomasBracho1987 @SIVN1 

CC: @AnjaliPandit20 @SIJAIEQUINOR

**Comment by luan-droid** [comment]
From what I understand, edges is the pop up message that is saying if you want to delete (card) or not. That functionality works fine. Tested in test

**Comment by luan-droid** [comment]
Looks like all the pop up messages are working fine, for deleting the process, main activity, sub activity, PQIR, linked processes and choice card.
