### ISSUE TITLE
Shifty display when showing snack-message

### ISSUE THREAD

**Issue by SjoenH** [equinor/MAD-VSM-WEB#89]
[vsm-154](https://equinor-sds-si.atlassian.net/browse/VSM-154)

**Comment by SjoenH** [comment]
Considering dropping the snack-message. Maybe it is not the best way to show progress?
But it might be good for error-messages... 🤔

**Comment by SjoenH** [comment]
@equinor/mad-testers Could we get this verified that it's ok now?

**Comment by ntorsen** [comment]
@SjoenH yes, I can verify on my end-
No shifty display
